### ISSUE TITLE
client should handle 0 byte reads from unexpected FIN

### ISSUE THREAD

**Issue by rjloura** [joyent/rust-fast#12]
While running multiple raw sql queries against a node-moray server I noticed that my process would hang after receiving anywhere from 20k to 100k records (200 - 1000 reads of chunks of 100) . 

Looking at `netstat` I see that the connection is in the CLOSE_WAIT state which means that it received a FIN.  Luckily this was easily reproducible and I was able to confirm that in fact a FIN was received and acknowledged.  Further investigation showed that my process was simply looping in the client.rs'receive() while loop.  Specifically the TcpStream hands up 0 bytes every time this function calls `stream.read()`.  The 0 byte buffer is passed to `parse_and_handle_messages()` which likely hits `Err(FastParseError::NotEnoughBytes(_bytes))` and returns `Ok(BufferAction::Keep)`, which matches to the unit type, and executes the `stream.read()` again... and around we go.

This seems to properly detect, and allow the consumer to handle the issue:
```
diff --git a/src/client.rs b/src/client.rs
index f9477fd..425f8bd 100644
--- a/src/client.rs
+++ b/src/client.rs
@@ -47,6 +47,14 @@ where
         let mut read_buf = [0; 128];
         match stream.read(&mut read_buf) {
             Ok(byte_count) => {
+                if byte_count == 0 {
+                    // Could also be ErrorKind::ConnectionAborted
+                    result = Err(
+                        Error::new(ErrorKind::UnexpectedEof,
+                            "Received EOF (0 bytes) from server"));
+                    stream_end = true;
+                }
+
                 total_bytes += byte_count;
                 msg_buf.extend_from_slice(&read_buf[0..byte_count]);
                 match parse_and_handle_messages(msg_buf.as_slice(), &mut response_handler) {

```

This only seems to happen immediately after a request is sent, so there is probably a more elegant way of handling this.  Regardless, it seems to me that in such a case rust-fast should simply pass up an error to its consumer and let the pre-mature connection close be handled at a higher level.  The main reason for this is because the connection is generic to rust-fast and is provided as a parameter for client actions (send/receive). 

Also, it is not clear why the node-moray server is sending the FIN (closing the connection).  That needs to be investigated.

**Comment by kellymclaughlin** [comment]
Nice catch! I don't know of a better way to deal with the passive close situation. 

I think your solution looks fine. I would probably just make another clause to the `match` statement that matches `Ok(0)` rather than have another level of nesting, but the error handling makes sense to me.
